### ISSUE TITLE
Clicking menu items in mobile/compact layout does not hide the menu

### ISSUE THREAD

**Issue by vytas7** [falconry/falconry.github.io#17]
On mobiles or otherwise narrow browser windows https://falconframework.org/ menu reduces to a mobile menu button and a popup menu, which is all good and expected in itself.

However, clicking menu items does not hide the menu itself, which keeps covering, depending on the device dimensions, a fair bit of the page, forcing one to manually hide it.

![image](https://user-images.githubusercontent.com/3430939/39448959-03393c16-4cc7-11e8-9b91-4b6cd294df15.png)

**Comment by CaselIT** [comment]
I can no longer reproduce. I guess it's fixed now

**Comment by vytas7** [comment]
I can still reproduce. Let me circle back on this tomorrow.

**Comment by CaselIT** [comment]
I've tried both ff desktop and mobile (on Android) and it's fine

**Comment by vytas7** [comment]
@CaselIT probably I haven't clearly explained what my expectation is.

https://user-images.githubusercontent.com/3430939/113432872-729f5700-93de-11eb-8932-c87058d7aec0.mp4

When clicking on the menu items, such as _Features_, _Benchmarks_, _About_ etc in the above example, I expect the menu to hide itself upon every click.
Because it is not practical to read text in the remaining uncovered tiny area, so the user would probably want to (unnecessarily) click on the menu button to hide it again.

**Comment by CaselIT** [comment]
oh ok! it was not clear before :) I though clicking on the hamburger menu was not working!

**Comment by vytas7** [comment]
"Hamburger" menu :rofl: :hamburger:
