### ISSUE TITLE
No link to documentation

### ISSUE THREAD

**Issue by freakboy3742** [falconry/falconry.github.io#19]
Landing at falconframework.org, there's several references to things being "well documented"... but there's no actual link to the documentation.

In particular, the one thing someone is likely to want to do when they discover the project is find a tutorial - but there's no mention of one.

**Comment by vytas7** [comment]
Hi @freakboy3742 !
Agreed!

This has already been pointed out a couple of times; we'll get this fixed for Falcon 3.0.

The documentation link is there on the front page, but its label is not very intuitive. It reads: "*Get started*" (the first button in the row right behind the banner).

**Comment by vytas7** [comment]
@freakboy3742 as per the PR referenced above, this has now been fixed.

https://falconframework.org/ -- the first button now reads ["**Read the Docs**"](https://falcon.readthedocs.io/).
